version: '3'

services:
  api:
    build: api
    command: ["flask", "run", "--host=0.0.0.0"]
    volumes:
      - ./api:/backend
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
    ports:
      - "5000:5000"

  client:
    depends_on:
      - api
    build: ./client
    stdin_open: true
    expose:
      - "3000"
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
